from django.urls import path, include
from rest_framework_nested import routers
from . import views

# Create a top-level router
router = routers.DefaultRouter()

# Register the viewsets for top-level resources
router.register(r'employees', views.EmployeeViewSet, basename='employee')
router.register(r'locations', views.LocationViewSet, basename='location')
router.register(r'shifts', views.ShiftViewSet, basename='shift')

# Create a nested router for employee availability
# This will create URLs like /employees/{employee_pk}/availability/
employees_router = routers.NestedSimpleRouter(router, r'employees', lookup='employee')
employees_router.register(r'availability', views.EmployeeAvailabilityViewSet, basename='employee-availability')

# The main urlpatterns for the app
urlpatterns = [
    # Include the URLs generated by the top-level router
    path('', include(router.urls)),
    # Include the URLs generated by the nested router
    path('', include(employees_router.urls)),
]