# Generated by Django 5.2.3 on 2025-06-25 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='end_time',
        ),
    ]
