# Generated by Django 5.2.3 on 2025-06-25 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_shift_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=28800)),
        ),
    ]
