# Generated by Django 5.2.3 on 2025-07-02 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_employeeavailability'),
    ]

    operations = [
    ]
