# Generated by Django 5.2.3 on 2025-07-02 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_remove_employee_first_name_remove_employee_last_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeavailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeeavailability',
            name='date',
            field=models.DateField(default=datetime.date(2025, 7, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='Unknown Employee', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeavailability',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='employeeavailability',
            unique_together={('employee', 'date')},
        ),
    ]
