# Generated by Django 5.2.3 on 2025-07-02 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_employeeavailability_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeavailability',
            name='day_of_week',
        ),
    ]
