# Generated by Django 5.2.3 on 2025-07-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_remove_employeeavailability_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='unavailable_days',
            field=models.CharField(blank=True, help_text='Comma-separated days of the week (0=Mon, 6=Sun)', max_length=15),
        ),
    ]
