# Generated by Django 5.2.3 on 2025-07-02 04:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_employee_unavailable_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeavailability',
            options={},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='allowed_locations',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='status',
        ),
        migrations.AddField(
            model_name='shift',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='unavailable_days',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeavailability',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='schedule.employee'),
        ),
        migrations.AlterField(
            model_name='employeeavailability',
            name='end_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='employeeavailability',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='schedule.employee'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='schedule.location'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
