# Generated by Django 5.2.3 on 2025-07-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_alter_shift_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='employees', to='schedule.location'),
        ),
    ]
