# Generated by Django 5.2.3 on 2025-07-04 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_employee_address_employee_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.employee'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.location'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('employee', 'date', 'start_time')},
        ),
    ]
